name: flutter_sheet_localization
description: Annotations for the flutter_sheet_localization_generator package.
version: 5.1.1
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  template_string:   
   git:
      url: https://github.com/Whering-Ltd/flutter_sheet_localization.git
      ref: update-intl-package
      path: template_string
