name: flutter_sheet_localization_generator
description: Flutter localizations code generator from Google sheet files.
version: 5.1.7
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: ">=3.35.1"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  meta: ^1.11.0
  csv: ^5.1.1
  recase: ^4.1.0
  code_builder: ^4.11.0
  dart_style: any
  source_gen: ^4.1.2
  flutter_sheet_localization:
    git:
      url: https://github.com/Whering-Ltd/flutter_sheet_localization.git
      ref: flutter-3.41.7-update
      path: flutter_sheet_localization
  build: ^4.0.0
  analyzer: ^10.0.0
  collection: ^1.18.0
  intl: '>=0.18.1 <=0.20.2'
  localization_builder:
    git:
      url: https://github.com/Whering-Ltd/flutter_sheet_localization.git
      ref: flutter-3.41.7-update
      path: localization_builder

dev_dependencies:
  build_test: ^3.5.5
  build_runner: ^2.10.5

dependency_overrides:
  dart_style:
    git:
      url: https://github.com/dart-lang/dart_style.git
      ref: main
