name: template_string
description: A simple command-line application.
version: 0.6.0
homepage: https://github.com/aloisdeniel/flutter_sheet_localization

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^3.0.0
