name: example
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  logging: ^1.0.0
  http: ^0.13.0
  csv:
  template_string:
    git:
      url: https://github.com/Whering-Ltd/flutter_sheet_localization.git
      ref: update-sdk
      path: template_string
  localization_builder: 
    path: ../